name: CD - Deploy PulseCheck to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.EC2_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> "$HOME/.ssh/known_hosts"


      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            if [ ! -d "PulseCheck" ]; then
              git clone https://github.com/Kirankumarvel/PulseCheck.git
            fi

            cd PulseCheck
            git pull origin main

            docker stop pulsecheck || true
            docker rm pulsecheck || true

            docker build -t pulsecheck:latest .

            docker run -d \
              --name pulsecheck \
              -p ${{ secrets.APP_PORT }}:${{ secrets.APP_PORT }} \
              --restart unless-stopped \
              pulsecheck:latest
          EOF
