name: CD - Deploy PulseCheck to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          rm -f "$HOME/.ssh"
          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"

          echo "${{ secrets.EC2_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"

          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> "$HOME/.ssh/known_hosts"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=yes ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -euxo pipefail

            echo "===> Who am I"
            whoami

            echo "===> Docker version"
            docker --version

            echo "===> Checking repo directory"
            if [ ! -d "$HOME/PulseCheck" ]; then
              echo "Cloning repository"
              git clone https://github.com/Kirankumarvel/PulseCheck.git
            fi

            cd $HOME/PulseCheck

            echo "===> Pulling latest code"
            git pull origin main

            echo "===> Stopping old container (if any)"
            docker stop pulsecheck || true
            docker rm pulsecheck || true

            echo "===> Building Docker image"
            docker build -t pulsecheck:latest .

            echo "===> Running container"
            docker run -d \
              --name pulsecheck \
              -p 8000:8000 \
              --restart unless-stopped \
              pulsecheck:latest

            echo "===> Running containers"
            docker ps
          EOF
